const H1=['A1','A2','A3','A4','A5','B1','B2','B3','B4','B5','C1','C2','C3','C4','C5','D1','D2','D3','D4','D5','E1','E2','E3','E4','E5','F1','F2','F3','F4','F5'];
const H2=Array.from({length:40},(_,i)=>String(i+1));
const demo={occupied:new Set(['A3','B2','12','27']),reserved:new Set(['A5','19']),student:{name:'Demo Student',id:'SPL001',seat:'A3',plan:'Hall 1 Full Time',validity:'15 Oct 2026',payment:'PAID',inside:false,checkin:null,total:0}};
let supabaseClient=null;if(window.SPL_CONFIG.SUPABASE_URL.startsWith('http')&&window.supabase){supabaseClient=supabase.createClient(window.SPL_CONFIG.SUPABASE_URL,window.SPL_CONFIG.SUPABASE_KEY)}
const $=s=>document.querySelector(s);const modal=m=>{$('#modalContent').innerHTML=m;$('#modal').classList.remove('hidden')};window.closeModal=()=>$('#modal').classList.add('hidden');
function renderSeats(){let html='';[['Hall 1 · Full Time · A1–F5',H1],['Hall 2 · Seats 1–40',H2]].forEach(([title,seats])=>{html+=`<div class="seat-hall"><h3>${title}</h3><div class="seat-grid">`;seats.forEach(s=>{let status=demo.student.inside&&s===demo.student.seat?'occupied':demo.occupied.has(s)?'occupied':demo.reserved.has(s)?'reserved':'available';let label=status==='occupied'?'Occupied':status==='reserved'?'Reserved':'Available';html+=`<button class="seat ${status}" onclick="seatAction('${s}','${status}')">${s}<small>${status==='occupied'&&s===demo.student.seat?'🟢 YOU':label}</small></button>`});html+='</div></div>'});$('#seatMap').innerHTML=html;$('#availableCount').textContent=70-demo.occupied.size-demo.reserved.size-(demo.student.inside&&!demo.occupied.has(demo.student.seat)?1:0);$('#insideCount').textContent=demo.student.inside?1:0}
window.seatAction=(seat,status)=>{if(status==='available'){modal(`<h2>Book seat ${seat}</h2><p>This demo seat is available. In production, your Supabase account will be checked before booking.</p><button class="btn btn-primary full" onclick="bookSeat('${seat}')">Confirm Seat</button>`)}else modal(`<h2>Seat ${seat}</h2><p>This seat is ${status}. ${status==='occupied'?'It is currently in use.':'It is reserved.'}</p>`)};
window.bookSeat=seat=>{demo.student.seat=seat;demo.reserved.delete(seat);demo.occupied.add(seat);closeModal();updateStudent();renderSeats();alert(`Seat ${seat} selected for the demo account.`)};
function updateStudent(){let s=demo.student;$('#studentName').textContent=s.name;$('#studentId').textContent='ID: '+s.id;$('#studentSeat').textContent=s.seat;$('#studentPlan').textContent=s.plan;$('#studentValidity').textContent=s.validity;$('#paymentStatus').textContent=s.payment;$('#liveBadge').textContent=s.inside?'🟢 In Library':'⚪ Checked Out';$('#checkBtn').textContent=s.inside?'CHECK OUT':'CHECK IN';$('#checkBtn').onclick=toggleAttendance;$('#studyTime').textContent=formatStudy()}
function formatStudy(){let ms=demo.student.total;if(demo.student.inside&&demo.student.checkin)ms+=Date.now()-demo.student.checkin;let min=Math.floor(ms/60000);return `${Math.floor(min/60)}h ${min%60}m`}
function toggleAttendance(){if(!demo.student.inside){if(demo.student.seat==='—')return alert('Please select a seat first.');demo.student.inside=true;demo.student.checkin=Date.now();demo.occupied.add(demo.student.seat)}else{demo.student.total+=Date.now()-demo.student.checkin;demo.student.inside=false;demo.student.checkin=null}updateStudent();renderSeats()}
function showQR(){modal(`<h2>Study Point Library — IN / OUT QR</h2><p>Place this permanent QR at the entrance. In production it should point to your portal URL.</p><div class="qr-placeholder" style="margin:20px auto"></div><p><b>Flow:</b> Scan → Login → Check In / Check Out</p>`)}
function notices(){const items=[['Welcome to Study Point Library','Maintain silence and use your assigned seat.'],['Membership renewal','Renew before your validity ends to keep your seat.'],['QR attendance','Use the single entrance QR for both IN and OUT.']];$('#noticeList').innerHTML=items.map(x=>`<div class="notice"><b>${x[0]}</b><span>${x[1]}</span></div>`).join('')}
window.selectPlan=p=>modal(`<h2>${p}</h2><p>Your selection will be saved to your membership request in the production version.</p><button class="btn btn-primary full" onclick="closeModal();alert('Membership request recorded in demo mode.')">Continue</button>`);
$('#loginBtn').onclick=()=>modal(`<h2>Student Login</h2><p>Production V2 will use Supabase Auth. For this starter, the demo student is already loaded.</p><button class="btn btn-primary full" onclick="closeModal();updateStudent()">Continue as Demo Student</button>`);
$('#qrBtn').onclick=showQR;$('#qrBtn2').onclick=showQR;$('#year').textContent=new Date().getFullYear();notices();updateStudent();renderSeats();setInterval(()=>{$('#studyTime').textContent=formatStudy()},30000);
